# Generated by Django 3.2.3 on 2021-07-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_quantity', models.CharField(max_length=20)),
                ('item_status', models.CharField(max_length=20)),
                ('user_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
