# Generated by Django 4.1.1 on 2022-10-19 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quary_email', models.CharField(max_length=50)),
                ('queary_contact_number', models.CharField(max_length=50)),
                ('queary_message', models.CharField(max_length=100)),
            ],
        ),
    ]
